# Loop Exercises

Your request is a continuation of a previous conversation where I provided exercises based on notes about loops in Python.

## Exercise 1: While Loop

Write a while loop that prints the numbers from 1 to 10.

In [2]:
#Write a while loop that prints the numbers from 1 to 10.
x=1
while x <= 10:
  print(x)
  x=x + 1

1
2
3
4
5
6
7
8
9
10

Create a while loop that calculates the sum of all numbers from 1 to 100.

In [7]:
#Create a while loop that calculates the sum of all numbers from 1 to 100.
x=0
list=[]
while x <= 100:
  list.append(x)
  x = x + 1

sum(list)

5050

# Exercise 2: For Loop

Create a list of your favorite fruits.

Use a for loop to print each fruit in the list.

Create a string. Use a for loop to print each character of the string in uppercase.

Given a list of numbers, use a for loop to find the sum of all the numbers.

In [8]:
# Creating list
fruits= ["apple", "pear", "orange", "banana", "kiwi"]

for fruit in fruits:
  print(fruit)

apple
pear
orange
banana
kiwi

In [13]:
# creating string
s="superman"
#looping letters in string
for letters in s:
  print(letters.capitalize())

S
U
P
E
R
M
A
N

In [19]:
#creating list
list=[1,2,3,4,5,12,14]
total_sum = 0  # Initialize a variable to store the sum

for i in range(len(list) - 1):
  total_sum = total_sum + list[i] + list[i + 1]

print(total_sum) # Print the total sum

67

## Exercise 3: Looping with Dictionaries

Create a dictionary where the keys are names and the values are ages.

Use a for loop to print the name and age of each person in the dictionary.

Modify the loop to print only the names.

In [22]:
# Creating dictionary
ages = { "Kevin": 24, "Tom": 56, "Sam":26, "Joe":30, "Sal":67}

#print names using loop
for name, age in ages.items():
  print( name + " is " + str(age) + " years old")

Kevin is 24 years old
Tom is 56 years old
Sam is 26 years old
Joe is 30 years old
Sal is 67 years old

In [27]:
#Modifying loop to print only names
for names in ages.items():
   print(names[0])

Kevin
Tom
Sam
Joe
Sal

# Exercise 4: Looping with NumPy Arrays

Create a NumPy array of 10 random numbers.

Use a for loop to print each number in the array.

Create a 2D NumPy array. Use a for loop (and np.nditer()) to print each element in the array.

In [29]:
#importing numpy
import numpy as np

#Creating array
list= [2,3,54,33,21,35,38,21,76,99]

#Converting to an array
array = np.array(list)
array

#Printing each number in the array with for loop
for n in np.nditer(array):
  print(n)

2
3
54
33
21
35
38
21
76
99

## Exercise 5: Looping with Pandas DataFrames

Load the "tips" dataset from seaborn.

Use a for loop and iterrows() to print the 'total_bill' and 'tip' for each row in the DataFrame.

Using a for loop and iterrows(), create a new column in the DataFrame that calculates the tip percentage.

In [45]:
#Loading tips data set
import seaborn as sns

tips_df = sns.load_dataset("tips")
tips_df

#printing total bill and tips
for label, row in tips_df.iterrows():
  print(label, row["total_bill"], row["tip"])

0 16.99 1.01
1 10.34 1.66
2 21.01 3.5
3 23.68 3.31
4 24.59 3.61
5 25.29 4.71
6 8.77 2.0
7 26.88 3.12
8 15.04 1.96
9 14.78 3.23
10 10.27 1.71
11 35.26 5.0
12 15.42 1.57
13 18.43 3.0
14 14.83 3.02
15 21.58 3.92
16 10.33 1.67
17 16.29 3.71
18 16.97 3.5
19 20.65 3.35
20 17.92 4.08
21 20.29 2.75
22 15.77 2.23
23 39.42 7.58
24 19.82 3.18
25 17.81 2.34
26 13.37 2.0
27 12.69 2.0
28 21.7 4.3
29 19.65 3.0
30 9.55 1.45
31 18.35 2.5
32 15.06 3.0
33 20.69 2.45
34 17.78 3.27
35 24.06 3.6
36 16.31 2.0
37 16.93 3.07
38 18.69 2.31
39 31.27 5.0
40 16.04 2.24
41 17.46 2.54
42 13.94 3.06
43 9.68 1.32
44 30.4 5.6
45 18.29 3.0
46 22.23 5.0
47 32.4 6.0
48 28.55 2.05
49 18.04 3.0
50 12.54 2.5
51 10.29 2.6
52 34.81 5.2
53 9.94 1.56
54 25.56 4.34
55 19.49 3.51
56 38.01 3.0
57 26.41 1.5
58 11.24 1.76
59 48.27 6.73
60 20.29 3.21
61 13.81 2.0
62 11.02 1.98
63 18.29 3.76
64 17.59 2.64
65 20.08 3.15
66 16.45 2.47
67 3.07 1.0
68 20.23 2.01
69 15.01 2.09
70 12.02 1.97
71 17.07 3.0
72 26.86 3.14
73 25.28 5.0
74 14.73 2.2
75 10.51 1.25
76 17.92 3.08
77 27.2 4.0
78 22.76 3.0
79 17.29 2.71
80 19.44 3.0
81 16.66 3.4
82 10.07 1.83
83 32.68 5.0
84 15.98 2.03
85 34.83 5.17
86 13.03 2.0
87 18.28 4.0
88 24.71 5.85
89 21.16 3.0
90 28.97 3.0
91 22.49 3.5
92 5.75 1.0
93 16.32 4.3
94 22.75 3.25
95 40.17 4.73
96 27.28 4.0
97 12.03 1.5
98 21.01 3.0
99 12.46 1.5
100 11.35 2.5
101 15.38 3.0
102 44.3 2.5
103 22.42 3.48
104 20.92 4.08
105 15.36 1.64
106 20.49 4.06
107 25.21 4.29
108 18.24 3.76
109 14.31 4.0
110 14.0 3.0
111 7.25 1.0
112 38.07 4.0
113 23.95 2.55
114 25.71 4.0
115 17.31 3.5
116 29.93 5.07
117 10.65 1.5
118 12.43 1.8
119 24.08 2.92
120 11.69 2.31
121 13.42 1.68
122 14.26 2.5
123 15.95 2.0
124 12.48 2.52
125 29.8 4.2
126 8.52 1.48
127 14.52 2.0
128 11.38 2.0
129 22.82 2.18
130 19.08 1.5
131 20.27 2.83
132 11.17 1.5
133 12.26 2.0
134 18.26 3.25
135 8.51 1.25
136 10.33 2.0
137 14.15 2.0
138 16.0 2.0
139 13.16 2.75
140 17.47 3.5
141 34.3 6.7
142 41.19 5.0
143 27.05 5.0
144 16.43 2.3
145 8.35 1.5
146 18.64 1.36
147 11.87 1.63
148 9.78 1.73
149 7.51 2.0
150 14.07 2.5
151 13.13 2.0
152 17.26 2.74
153 24.55 2.0
154 19.77 2.0
155 29.85 5.14
156 48.17 5.0
157 25.0 3.75
158 13.39 2.61
159 16.49 2.0
160 21.5 3.5
161 12.66 2.5
162 16.21 2.0
163 13.81 2.0
164 17.51 3.0
165 24.52 3.48
166 20.76 2.24
167 31.71 4.5
168 10.59 1.61
169 10.63 2.0
170 50.81 10.0
171 15.81 3.16
172 7.25 5.15
173 31.85 3.18
174 16.82 4.0
175 32.9 3.11
176 17.89 2.0
177 14.48 2.0
178 9.6 4.0
179 34.63 3.55
180 34.65 3.68
181 23.33 5.65
182 45.35 3.5
183 23.17 6.5
184 40.55 3.0
185 20.69 5.0
186 20.9 3.5
187 30.46 2.0
188 18.15 3.5
189 23.1 4.0
190 15.69 1.5
191 19.81 4.19
192 28.44 2.56
193 15.48 2.02
194 16.58 4.0
195 7.56 1.44
196 10.34 2.0
197 43.11 5.0
198 13.0 2.0
199 13.51 2.0
200 18.71 4.0
201 12.74 2.01
202 13.0 2.0
203 16.4 2.5
204 20.53 4.0
205 16.47 3.23
206 26.59 3.41
207 38.73 3.0
208 24.27 2.03
209 12.76 2.23
210 30.06 2.0
211 25.89 5.16
212 48.33 9.0
213 13.27 2.5
214 28.17 6.5
215 12.9 1.1
216 28.15 3.0
217 11.59 1.5
218 7.74 1.44
219 30.14 3.09
220 12.16 2.2
221 13.42 3.48
222 8.58 1.92
223 15.98 3.0
224 13.42 1.58
225 16.27 2.5
226 10.09 2.0
227 20.45 3.0
228 13.28 2.72
229 22.12 2.88
230 24.01 2.0
231 15.69 3.0
232 11.61 3.39
233 10.77 1.47
234 15.53 3.0
235 10.07 1.25
236 12.6 1.0
237 32.83 1.17
238 35.83 4.67
239 29.03 5.92
240 27.18 2.0
241 22.67 2.0
242 17.82 1.75
243 18.78 3.0

In [50]:
# create a new column in the DataFrame that calculates the tip percentage.
for label, row in tips_df.iterrows():
  tips_df["tip %"]=row["tip"]/row["total_bill"]

TypeError: 'float' object does not support item assignment

In [52]:
# create a new column in the DataFrame that calculates the tip percentage.
#quicker do it this way
tips_df["tip %"] = (tips_df["tip"] / tips_df["total_bill"])
tips_df

     total_bill   tip     sex smoker   day    time  size     tip %
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

Completed on the 06Feb2025. Sanjo Babatunde